fragment PageGoods on GoodsPageEntity {
    id
    attributes {
        pageTitle
        title
        good(pagination: {page: $page, pageSize: $pageSize}, filters: {price: $price, tag: $tag}) {
            ...ShoeCarouselCard
        }
    }
}