fragment PageGoods on GoodsPageEntity {
    id
    attributes {
        pageTitle
        title
        good(pagination: {page: $page, pageSize: $pageSize}) {
            ...ShoeCarouselCard
        }
    }
}