query getGoodsPage($pageTitle: String, $page: Int, $pageSize: Int) {
     sectionShoes(filters: {pageSubtitle: {eqi: $pageTitle}}, pagination: {page: $page, pageSize: $pageSize} ){
          data {
                   id
                   attributes {
                     ...SectionShoeFragment
                   }
                 }
    }
}
