query getGoodsPage($pageTitle: StringFilterInput, $page: Int, $pageSize: Int, $tag: StringFilterInput, $price: StringFilterInput) {
     goodsPages(filters:{pageTitle: $pageTitle}){
          data {
            ...PageGoods
          }
    }
}
