query getSectionMembership($id: ID, $locale: I18NLocaleCode) {
  sectionMembership(id: $id, locale: $locale) {
    data {
      id
      attributes {
        ...SectionMembershipFragment
      }
    }
  }
}