fragment SectionMainTitleFragment on SectionMainTitle {
    MainTitle
    SubTitle
    Video {
        data {
            attributes {
                ...FileFragment
            }
        }
    }
    ShowCollectionLinkButton {
        ...ButtonFragment
    }
    WatchLinkButton {
        ...ButtonFragment
    }
    Title
    publishedAt
}