fragment SectionShoeFragment on SectionShoe {
   addToBagButton {
        ...ButtonFragment
   }
   favoriteButton {
        ...ButtonFragment
   }
   options {
       ...ShoeOptionFragment
   }
   sizes {
        id
        Sizes {
            ...Size
        }
   }
   tags
   gender
   pageTitle
   pageSubtitle
   pageTitle2
   pageTitle3
   updatedAt
}