fragment ShoeOptionFragment on ComponentEntityShoeOption {
  mainImage {
    data {
      attributes {
        ...FileFragment
      }
    }
  }
  medias {
    data {
      attributes {
        ...FileFragment
      }
    }
  }
  title
  tag
  price
  description
}
